# Generated by Django 3.0.5 on 2020-05-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('designation', models.CharField(blank=True, max_length=30, null=True)),
                ('room_no', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rent_Ammount', models.IntegerField()),
                ('advance_Ammount', models.IntegerField()),
                ('contact_no', models.IntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionMonth', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('dueAmnt', models.IntegerField()),
                ('eBill', models.IntegerField()),
                ('mCharge', models.IntegerField(blank=True, null=True)),
                ('paymentDate', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Person')),
            ],
        ),
    ]
