# Generated by Django 3.0.5 on 2020-05-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20200509_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='mCharge',
            new_name='Maintanace_charge',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='eBill',
            new_name='electric_bill',
        ),
    ]
