# Generated by Django 3.0.5 on 2020-05-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20200509_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='dueAmnt',
            field=models.IntegerField(null=True),
        ),
    ]
