# Generated by Django 3.0.5 on 2020-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20200510_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontrack',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
