# Generated by Django 3.0.5 on 2020-05-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20200510_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
