# Generated by Django 3.0.5 on 2020-05-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20200511_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
